#Initialize image and install deps
FROM node:24-alpine
WORKDIR /usr/src
RUN adduser -D frontend && adduser frontend frontend
COPY --chown=frontend:frontend ./package.json ./
RUN npm install

#Copy the code in
COPY --chown=frontend:frontend ./*.* ./
COPY --chown=frontend:frontend ./src/. ./src/
RUN chown frontend:frontend ./ && chown frontend:frontend /usr/src/node_modules/
USER frontend:frontend
EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host"]