package swp391.group6.model;

public enum NotificationType {

    // CUSTOMER
    ORDER_CONFIRMATION,
    ORDER_STATUS_UPDATE,
    DELIVERY_COMPLETED,
    SUPPORT_TICKET_RESOLVED,
    BLOG_STATUS_UPDATE,
    SUPPORT_TICKET_UPDATE,
    WISHLIST_PRODUCT_BACK_IN_STOCK,
    RETURN_REQUEST_APPROVED,
    RETURN_REQUEST_REJECTED,
    RETURN_MORE_INFO_REQUIRED,
    RETURN_REFUND_PROCESSED,
    RETURN_ADDITIONAL_PAYMENT_REQUIRED,

    // MANAGER
    NEW_ORDER_ALERT,
    BLOG_PENDING_APPROVAL,
    RETURN_REQUEST_CREATED,

    // SHIPPER
    DELIVERY_ASSIGNMENT,

    // SUPPORT
    NEW_SUPPORT_REQUEST,

    // SYSTEM
    DELIVERY_EXCEPTION
}