export const SHIPPING_PROVINCES = [
  {
    value: 'Hà Nội',
    label: 'Hà Nội',
    districts: [
      {
        value: 'Quận Hoàn Kiếm',
        label: 'Quận Hoàn Kiếm',
        wards: [
          { value: 'Phường Cửa Nam', label: 'Phường Cửa Nam' },
          { value: 'Phường Hàng Bạc', label: 'Phường Hàng Bạc' },
          { value: 'Phường Hàng Buồm', label: 'Phường Hàng Buồm' },
          { value: 'Phường Hàng Đào', label: 'Phường Hàng Đào' },
          { value: 'Phường Hàng Mã', label: 'Phường Hàng Mã' },
          { value: 'Phường Hàng Trống', label: 'Phường Hàng Trống' },
          { value: 'Phường Lý Thái Tổ', label: 'Phường Lý Thái Tổ' },
          { value: 'Phường Phan Chu Trinh', label: 'Phường Phan Chu Trinh' },
          { value: 'Phường Tràng Tiền', label: 'Phường Tràng Tiền' },
          { value: 'Phường Trần Hưng Đạo', label: 'Phường Trần Hưng Đạo' },
        ],
      },
      {
        value: 'Quận Ba Đình',
        label: 'Quận Ba Đình',
        wards: [
          { value: 'Phường Cống Vị', label: 'Phường Cống Vị' },
          { value: 'Phường Điện Biên', label: 'Phường Điện Biên' },
          { value: 'Phường Đội Cấn', label: 'Phường Đội Cấn' },
          { value: 'Phường Giang Văn Minh', label: 'Phường Giang Văn Minh' },
          { value: 'Phường Kim Mã', label: 'Phường Kim Mã' },
          { value: 'Phường Liễu Giai', label: 'Phường Liễu Giai' },
          { value: 'Phường Ngọc Hà', label: 'Phường Ngọc Hà' },
          { value: 'Phường Ngọc Khánh', label: 'Phường Ngọc Khánh' },
          { value: 'Phường Phúc Xá', label: 'Phường Phúc Xá' },
          { value: 'Phường Quán Thánh', label: 'Phường Quán Thánh' },
          { value: 'Phường Thành Công', label: 'Phường Thành Công' },
          { value: 'Phường Trúc Bạch', label: 'Phường Trúc Bạch' },
          { value: 'Phường Vĩnh Phúc', label: 'Phường Vĩnh Phúc' },
        ],
      },
      {
        value: 'Quận Đống Đa',
        label: 'Quận Đống Đa',
        wards: [
          { value: 'Phường Cát Linh', label: 'Phường Cát Linh' },
          { value: 'Phường Hàng Bột', label: 'Phường Hàng Bột' },
          { value: 'Phường Khâm Thiên', label: 'Phường Khâm Thiên' },
          { value: 'Phường Khương Thượng', label: 'Phường Khương Thượng' },
          { value: 'Phường Láng Hạ', label: 'Phường Láng Hạ' },
          { value: 'Phường Láng Thượng', label: 'Phường Láng Thượng' },
          { value: 'Phường Nam Đồng', label: 'Phường Nam Đồng' },
          { value: 'Phường Ngã Tư Sở', label: 'Phường Ngã Tư Sở' },
          { value: 'Phường Ô Chợ Dừa', label: 'Phường Ô Chợ Dừa' },
          { value: 'Phường Quang Trung', label: 'Phường Quang Trung' },
          { value: 'Phường Thịnh Quang', label: 'Phường Thịnh Quang' },
          { value: 'Phường Thổ Quan', label: 'Phường Thổ Quan' },
          { value: 'Phường Trung Liệt', label: 'Phường Trung Liệt' },
          { value: 'Phường Trung Phụng', label: 'Phường Trung Phụng' },
          { value: 'Phường Văn Miếu', label: 'Phường Văn Miếu' },
        ],
      },
      {
        value: 'Quận Hai Bà Trưng',
        label: 'Quận Hai Bà Trưng',
        wards: [
          { value: 'Phường Bạch Đằng', label: 'Phường Bạch Đằng' },
          { value: 'Phường Bách Khoa', label: 'Phường Bách Khoa' },
          { value: 'Phường Cầu Đất', label: 'Phường Cầu Đất' },
          { value: 'Phường Đống Mác', label: 'Phường Đống Mác' },
          { value: 'Phường Đồng Nhân', label: 'Phường Đồng Nhân' },
          { value: 'Phường Đồng Tâm', label: 'Phường Đồng Tâm' },
          { value: 'Phường Lê Đại Hành', label: 'Phường Lê Đại Hành' },
          { value: 'Phường Minh Khai', label: 'Phường Minh Khai' },
          { value: 'Phường Ngô Quyền', label: 'Phường Ngô Quyền' },
          { value: 'Phường Phạm Đình Hổ', label: 'Phường Phạm Đình Hổ' },
          { value: 'Phường Phố Huế', label: 'Phường Phố Huế' },
          { value: 'Phường Quỳnh Lôi', label: 'Phường Quỳnh Lôi' },
          { value: 'Phường Quỳnh Mai', label: 'Phường Quỳnh Mai' },
          { value: 'Phường Thanh Lương', label: 'Phường Thanh Lương' },
          { value: 'Phường Thanh Nhàn', label: 'Phường Thanh Nhàn' },
          { value: 'Phường Trương Định', label: 'Phường Trương Định' },
        ],
      },
      {
        value: 'Quận Tây Hồ',
        label: 'Quận Tây Hồ',
        wards: [
          { value: 'Phường Bưởi', label: 'Phường Bưởi' },
          { value: 'Phường Thụy Khuê', label: 'Phường Thụy Khuê' },
          { value: 'Phường Thụy Phương', label: 'Phường Thụy Phương' },
          { value: 'Phường Tứ Liên', label: 'Phường Tứ Liên' },
          { value: 'Phường Xuân La', label: 'Phường Xuân La' },
          { value: 'Phường Yên Phụ', label: 'Phường Yên Phụ' },
        ],
      },
      {
        value: 'Quận Cầu Giấy',
        label: 'Quận Cầu Giấy',
        wards: [
          { value: 'Phường Dịch Vọng', label: 'Phường Dịch Vọng' },
          { value: 'Phường Dịch Vọng Hậu', label: 'Phường Dịch Vọng Hậu' },
          { value: 'Phường Mai Dịch', label: 'Phường Mai Dịch' },
          { value: 'Phường Nghĩa Đô', label: 'Phường Nghĩa Đô' },
          { value: 'Phường Nghĩa Tân', label: 'Phường Nghĩa Tân' },
          { value: 'Phường Quan Hoa', label: 'Phường Quan Hoa' },
          { value: 'Phường Trung Hòa', label: 'Phường Trung Hòa' },
          { value: 'Phường Yên Hòa', label: 'Phường Yên Hòa' },
        ],
      },
      {
        value: 'Quận Thanh Xuân',
        label: 'Quận Thanh Xuân',
        wards: [
          { value: 'Phường Hạ Đình', label: 'Phường Hạ Đình' },
          { value: 'Phường Khương Đình', label: 'Phường Khương Đình' },
          { value: 'Phường Khương Mai', label: 'Phường Khương Mai' },
          { value: 'Phường Khương Trung', label: 'Phường Khương Trung' },
          { value: 'Phường Kim Giang', label: 'Phường Kim Giang' },
          { value: 'Phường Nhân Chính', label: 'Phường Nhân Chính' },
          { value: 'Phường Phương Liệt', label: 'Phường Phương Liệt' },
          { value: 'Phường Thanh Xuân Bắc', label: 'Phường Thanh Xuân Bắc' },
          { value: 'Phường Thanh Xuân Nam', label: 'Phường Thanh Xuân Nam' },
          { value: 'Phường Thanh Xuân Trung', label: 'Phường Thanh Xuân Trung' },
        ],
      },
      {
        value: 'Quận Hà Đông',
        label: 'Quận Hà Đông',
        wards: [
          { value: 'Phường Biên Giang', label: 'Phường Biên Giang' },
          { value: 'Phường Đồng Mai', label: 'Phường Đồng Mai' },
          { value: 'Phường Dương Nội', label: 'Phường Dương Nội' },
          { value: 'Phường Hà Cầu', label: 'Phường Hà Cầu' },
          { value: 'Phường La Khê', label: 'Phường La Khê' },
          { value: 'Phường Mộ Lao', label: 'Phường Mộ Lao' },
          { value: 'Phường Nguyễn Trãi', label: 'Phường Nguyễn Trãi' },
          { value: 'Phường Phú La', label: 'Phường Phú La' },
          { value: 'Phường Phú Lãm', label: 'Phường Phú Lãm' },
          { value: 'Phường Phú Lương', label: 'Phường Phú Lương' },
          { value: 'Phường Quang Trung', label: 'Phường Quang Trung' },
          { value: 'Phường Vạn Phúc', label: 'Phường Vạn Phúc' },
          { value: 'Phường Văn Quán', label: 'Phường Văn Quán' },
          { value: 'Phường Yên Nghĩa', label: 'Phường Yên Nghĩa' },
          { value: 'Phường Yết Kiêu', label: 'Phường Yết Kiêu' },
        ],
      },
      {
        value: 'Quận Long Biên',
        label: 'Quận Long Biên',
        wards: [
          { value: 'Phường Bồ Đề', label: 'Phường Bồ Đề' },
          { value: 'Phường Cự Khối', label: 'Phường Cự Khối' },
          { value: 'Phường Đức Giang', label: 'Phường Đức Giang' },
          { value: 'Phường Gia Thụy', label: 'Phường Gia Thụy' },
          { value: 'Phường Giang Biên', label: 'Phường Giang Biên' },
          { value: 'Phường Long Biên', label: 'Phường Long Biên' },
          { value: 'Phường Ngọc Lâm', label: 'Phường Ngọc Lâm' },
          { value: 'Phường Ngọc Thụy', label: 'Phường Ngọc Thụy' },
          { value: 'Phường Phúc Đồng', label: 'Phường Phúc Đồng' },
          { value: 'Phường Phúc Lợi', label: 'Phường Phúc Lợi' },
          { value: 'Phường Sài Đồng', label: 'Phường Sài Đồng' },
          { value: 'Phường Thạch Bàn', label: 'Phường Thạch Bàn' },
          { value: 'Phường Việt Hưng', label: 'Phường Việt Hưng' },
        ],
      },
      {
        value: 'Quận Nam Từ Liêm',
        label: 'Quận Nam Từ Liêm',
        wards: [
          { value: 'Phường Cầu Diễn', label: 'Phường Cầu Diễn' },
          { value: 'Phường Đại Mỗ', label: 'Phường Đại Mỗ' },
          { value: 'Phường Mễ Trì', label: 'Phường Mễ Trì' },
          { value: 'Phường Mỹ Đình 1', label: 'Phường Mỹ Đình 1' },
          { value: 'Phường Mỹ Đình 2', label: 'Phường Mỹ Đình 2' },
          { value: 'Phường Phú Đô', label: 'Phường Phú Đô' },
          { value: 'Phường Tây Mỗ', label: 'Phường Tây Mỗ' },
          { value: 'Phường Thượng Đỉnh', label: 'Phường Thượng Đỉnh' },
          { value: 'Phường Trung Văn', label: 'Phường Trung Văn' },
          { value: 'Phường Xuân Phương', label: 'Phường Xuân Phương' },
        ],
      },
      {
        value: 'Quận Bắc Từ Liêm',
        label: 'Quận Bắc Từ Liêm',
        wards: [
          { value: 'Phường Cờ Lách', label: 'Phường Cờ Lách' },
          { value: 'Phường Đông Ngạc', label: 'Phường Đông Ngạc' },
          { value: 'Phường Đức Thắng', label: 'Phường Đức Thắng' },
          { value: 'Phường Liên Mạc', label: 'Phường Liên Mạc' },
          { value: 'Phường Minh Khai', label: 'Phường Minh Khai' },
          { value: 'Phường Phú Diễn', label: 'Phường Phú Diễn' },
          { value: 'Phường Phúc Diễn', label: 'Phường Phúc Diễn' },
          { value: 'Phường Tây Tự Du', label: 'Phường Tây Tự Du' },
          { value: 'Phường Thượng Cổ', label: 'Phường Thượng Cổ' },
          { value: 'Phường Thụy Phương', label: 'Phường Thụy Phương' },
          { value: 'Phường Xuân Đỉnh', label: 'Phường Xuân Đỉnh' },
          { value: 'Phường Xuân Tảo', label: 'Phường Xuân Tảo' },
        ],
      },
      {
        value: 'Quận Hoàng Mai',
        label: 'Quận Hoàng Mai',
        wards: [
          { value: 'Phường Đại Kim', label: 'Phường Đại Kim' },
          { value: 'Phường Định Công', label: 'Phường Định Công' },
          { value: 'Phường Giáp Bát', label: 'Phường Giáp Bát' },
          { value: 'Phường Hoàng Liệt', label: 'Phường Hoàng Liệt' },
          { value: 'Phường Hoàng Văn Thụ', label: 'Phường Hoàng Văn Thụ' },
          { value: 'Phường Lĩnh Nam', label: 'Phường Lĩnh Nam' },
          { value: 'Phường Mai Động', label: 'Phường Mai Động' },
          { value: 'Phường Tân Mai', label: 'Phường Tân Mai' },
          { value: 'Phường Thanh Trì', label: 'Phường Thanh Trì' },
          { value: 'Phường Thịnh Liệt', label: 'Phường Thịnh Liệt' },
          { value: 'Phường Trần Phú', label: 'Phường Trần Phú' },
          { value: 'Phường Vĩnh Hưng', label: 'Phường Vĩnh Hưng' },
          { value: 'Phường Yên Sở', label: 'Phường Yên Sở' },
        ],
      },
      {
        value: 'Huyện Thanh Trì',
        label: 'Huyện Thanh Trì',
        wards: [
          { value: 'Phường Đại Áng', label: 'Phường Đại Áng' },
          { value: 'Phường Đông Mỹ', label: 'Phường Đông Mỹ' },
          { value: 'Phường Liễu Trì', label: 'Phường Liễu Trì' },
          { value: 'Phường Ngọc Hồi', label: 'Phường Ngọc Hồi' },
          { value: 'Phường Tả Thanh Oai', label: 'Phường Tả Thanh Oai' },
          { value: 'Phường Tam Hiệp', label: 'Phường Tam Hiệp' },
          { value: 'Phường Tân Triều', label: 'Phường Tân Triều' },
          { value: 'Phường Thanh Liệt', label: 'Phường Thanh Liệt' },
          { value: 'Phường Tứ Hiệp', label: 'Phường Tứ Hiệp' },
          { value: 'Phường Vĩnh Quỳnh', label: 'Phường Vĩnh Quỳnh' },
          { value: 'Phường Yên Mỹ', label: 'Phường Yên Mỹ' },
        ],
      },
      {
        value: 'Huyện Gia Lâm',
        label: 'Huyện Gia Lâm',
        wards: [
          { value: 'Thị trấn Trâu Quỳ', label: 'Thị trấn Trâu Quỳ' },
          { value: 'Thị trấn Yên Viên', label: 'Thị trấn Yên Viên' },
          { value: 'Xã Bát Tràng', label: 'Xã Bát Tràng' },
          { value: 'Xã Cổ Bi', label: 'Xã Cổ Bi' },
          { value: 'Xã Đa Tốn', label: 'Xã Đa Tốn' },
          { value: 'Xã Đặng Xá', label: 'Xã Đặng Xá' },
          { value: 'Xã Đình Xá', label: 'Xã Đình Xá' },
          { value: 'Xã Dương Hà', label: 'Xã Dương Hà' },
          { value: 'Xã Dương Quang', label: 'Xã Dương Quang' },
          { value: 'Xã Dương Xá', label: 'Xã Dương Xá' },
          { value: 'Xã Kiêu Kỵ', label: 'Xã Kiêu Kỵ' },
          { value: 'Xã Kim Lan', label: 'Xã Kim Lan' },
          { value: 'Xã Kim Sơn', label: 'Xã Kim Sơn' },
          { value: 'Xã Ninh Hiệp', label: 'Xã Ninh Hiệp' },
          { value: 'Xã Phù Đổng', label: 'Xã Phù Đổng' },
          { value: 'Xã Trung Mầu', label: 'Xã Trung Mầu' },
          { value: 'Xã Văn Đức', label: 'Xã Văn Đức' },
          { value: 'Xã Yên Thường', label: 'Xã Yên Thường' },
          { value: 'Xã Yên Viên', label: 'Xã Yên Viên' },
        ],
      },
      {
        value: 'Huyện Đông Anh',
        label: 'Huyện Đông Anh',
        wards: [
          { value: 'Thị trấn Đông Anh', label: 'Thị trấn Đông Anh' },
          { value: 'Xã Bắc Hồng', label: 'Xã Bắc Hồng' },
          { value: 'Xã Cổ Loa', label: 'Xã Cổ Loa' },
          { value: 'Xã Đại Mạch', label: 'Xã Đại Mạch' },
          { value: 'Xã Đản Dị', label: 'Xã Đản Dị' },
          { value: 'Xã Duyên Hải', label: 'Xã Duyên Hải' },
          { value: 'Xã Hải Bối', label: 'Xã Hải Bối' },
          { value: 'Xã Hồng Hà', label: 'Xã Hồng Hà' },
          { value: 'Xã Kim Chung', label: 'Xã Kim Chung' },
          { value: 'Xã Kim Nỗ', label: 'Xã Kim Nỗ' },
          { value: 'Xã Liên Hà', label: 'Xã Liên Hà' },
          { value: 'Xã Mai Lâm', label: 'Xã Mai Lâm' },
          { value: 'Xã Nam Hồng', label: 'Xã Nam Hồng' },
          { value: 'Xã Nguyên Khê', label: 'Xã Nguyên Khê' },
          { value: 'Xã Tàm Xá', label: 'Xã Tàm Xá' },
          { value: 'Xã Thụy Lâm', label: 'Xã Thụy Lâm' },
          { value: 'Xã Tiên Dương', label: 'Xã Tiên Dương' },
          { value: 'Xã Uy Nỗ', label: 'Xã Uy Nỗ' },
          { value: 'Xã Vân Hà', label: 'Xã Vân Hà' },
          { value: 'Xã Vân Nội', label: 'Xã Vân Nội' },
          { value: 'Xã Việt Hùng', label: 'Xã Việt Hùng' },
          { value: 'Xã Võng La', label: 'Xã Võng La' },
          { value: 'Xã Xuân Nộn', label: 'Xã Xuân Nộn' },
        ],
      },
      {
        value: 'Huyện Sóc Sơn',
        label: 'Huyện Sóc Sơn',
        wards: [
          { value: 'Thị trấn Sóc Sơn', label: 'Thị trấn Sóc Sơn' },
          { value: 'Xã Bắc Phú', label: 'Xã Bắc Phú' },
          { value: 'Xã Hiền Ninh', label: 'Xã Hiền Ninh' },
          { value: 'Xã Hồng Kỳ', label: 'Xã Hồng Kỳ' },
          { value: 'Xã Kim Long', label: 'Xã Kim Long' },
          { value: 'Xã Mai Đình', label: 'Xã Mai Đình' },
          { value: 'Xã Minh Châu', label: 'Xã Minh Châu' },
          { value: 'Xã Minh Trí', label: 'Xã Minh Trí' },
          { value: 'Xã Nam Phú', label: 'Xã Nam Phú' },
          { value: 'Xã Phù Linh', label: 'Xã Phù Linh' },
          { value: 'Xã Phú Cường', label: 'Xã Phú Cường' },
          { value: 'Xã Phú Minh', label: 'Xã Phú Minh' },
          { value: 'Xã Quang Tiến', label: 'Xã Quang Tiến' },
          { value: 'Xã Tân Dân', label: 'Xã Tân Dân' },
          { value: 'Xã Tân Hưng', label: 'Xã Tân Hưng' },
          { value: 'Xã Thanh Xuân', label: 'Xã Thanh Xuân' },
          { value: 'Xã Tiên Phong', label: 'Xã Tiên Phong' },
          { value: 'Xã Trung Giã', label: 'Xã Trung Giã' },
          { value: 'Xã Xuân Giang', label: 'Xã Xuân Giang' },
          { value: 'Xã Xuân Thu', label: 'Xã Xuân Thu' },
        ],
      },
      {
        value: 'Huyện Thường Tín',
        label: 'Huyện Thường Tín',
        wards: [
          { value: 'Thị trấn Thường Tín', label: 'Thị trấn Thường Tín' },
          { value: 'Xã Chương Dương', label: 'Xã Chương Dương' },
          { value: 'Xã Dũng Tiến', label: 'Xã Dũng Tiến' },
          { value: 'Xã Duyên Thái', label: 'Xã Duyên Thái' },
          { value: 'Xã Hà Hồi', label: 'Xã Hà Hồi' },
          { value: 'Xã Hiền Giáo', label: 'Xã Hiền Giáo' },
          { value: 'Xã Hòa Bình', label: 'Xã Hòa Bình' },
          { value: 'Xã Khánh Hà', label: 'Xã Khánh Hà' },
          { value: 'Xã Lê Lợi', label: 'Xã Lê Lợi' },
          { value: 'Xã Liên Phương', label: 'Xã Liên Phương' },
          { value: 'Xã Minh Cường', label: 'Xã Minh Cường' },
          { value: 'Xã Nghiêm Xuyên', label: 'Xã Nghiêm Xuyên' },
          { value: 'Xã Nguyễn Trãi', label: 'Xã Nguyễn Trãi' },
          { value: 'Xã Ninh Sở', label: 'Xã Ninh Sở' },
          { value: 'Xã Quất Động', label: 'Xã Quất Động' },
          { value: 'Xã Tân Minh', label: 'Xã Tân Minh' },
          { value: 'Xã Thắng Lợi', label: 'Xã Thắng Lợi' },
          { value: 'Xã Thống Nhất', label: 'Xã Thống Nhất' },
          { value: 'Xã Tiền Phong', label: 'Xã Tiền Phong' },
          { value: 'Xã Tô Hiệu', label: 'Xã Tô Hiệu' },
          { value: 'Xã Vạn Điểm', label: 'Xã Vạn Điểm' },
          { value: 'Xã Văn Bình', label: 'Xã Văn Bình' },
          { value: 'Xã Văn Phú', label: 'Xã Văn Phú' },
        ],
      },
      {
        value: 'Huyện Phú Xuyên',
        label: 'Huyện Phú Xuyên',
        wards: [
          { value: 'Thị trấn Phú Xuyên', label: 'Thị trấn Phú Xuyên' },
          { value: 'Thị trấn Xuân Dương', label: 'Thị trấn Xuân Dương' },
          { value: 'Xã Bạch Hạ', label: 'Xã Bạch Hạ' },
          { value: 'Xã Châu Can', label: 'Xã Châu Can' },
          { value: 'Xã Đại Thắng', label: 'Xã Đại Thắng' },
          { value: 'Xã Hoàng Long', label: 'Xã Hoàng Long' },
          { value: 'Xã Hồng Thái', label: 'Xã Hồng Thái' },
          { value: 'Xã Khai Thái', label: 'Xã Khai Thái' },
          { value: 'Xã Minh Tân', label: 'Xã Minh Tân' },
          { value: 'Xã Mỹ Đức', label: 'Xã Mỹ Đức' },
          { value: 'Xã Nam Phong', label: 'Xã Nam Phong' },
          { value: 'Xã Phúc Tiến', label: 'Xã Phúc Tiến' },
          { value: 'Xã Phương Dinh', label: 'Xã Phương Dinh' },
          { value: 'Xã Quang Lãm', label: 'Xã Quang Lãm' },
          { value: 'Xã Quang Trung', label: 'Xã Quang Trung' },
          { value: 'Xã Sơn Hà', label: 'Xã Sơn Hà' },
          { value: 'Xã Tân Dân', label: 'Xã Tân Dân' },
          { value: 'Xã Thụy Phú', label: 'Xã Thụy Phú' },
          { value: 'Xã Tri Thủy', label: 'Xã Tri Thủy' },
          { value: 'Xã Vân Từ', label: 'Xã Vân Từ' },
        ],
      },
      {
        value: 'Huyện Chương Mỹ',
        label: 'Huyện Chương Mỹ',
        wards: [
          { value: 'Thị trấn Chúc Sơn', label: 'Thị trấn Chúc Sơn' },
          { value: 'Thị trấn Xuân Mai', label: 'Thị trấn Xuân Mai' },
          { value: 'Xã Đại Yên', label: 'Xã Đại Yên' },
          { value: 'Xã Đồng Lạc', label: 'Xã Đồng Lạc' },
          { value: 'Xã Đồng Phú', label: 'Xã Đồng Phú' },
          { value: 'Xã Hòa Chính', label: 'Xã Hòa Chính' },
          { value: 'Xã Hữu Cước', label: 'Xã Hữu Cước' },
          { value: 'Xã Lam Điền', label: 'Xã Lam Điền' },
          { value: 'Xã Mỹ Lương', label: 'Xã Mỹ Lương' },
          { value: 'Xã Nam Phương Tiến', label: 'Xã Nam Phương Tiến' },
          { value: 'Xã Ngọc Hưng', label: 'Xã Ngọc Hưng' },
          { value: 'Xã Phú Nam An', label: 'Xã Phú Nam An' },
          { value: 'Xã Phụng Châu', label: 'Xã Phụng Châu' },
          { value: 'Xã Quảng Bị', label: 'Xã Quảng Bị' },
          { value: 'Xã Thanh Bình', label: 'Xã Thanh Bình' },
          { value: 'Xã Thượng Vực', label: 'Xã Thượng Vực' },
          { value: 'Xã Tiên Phương', label: 'Xã Tiên Phương' },
          { value: 'Xã Trần Phú', label: 'Xã Trần Phú' },
          { value: 'Xã Trung Hòa', label: 'Xã Trung Hòa' },
          { value: 'Xã Vạn Thắng', label: 'Xã Vạn Thắng' },
          { value: 'Xã Viên Động', label: 'Xã Viên Động' },
        ],
      },
    ],
  },
]

export const getDistrictsByProvince = (provinceValue) => {
  const province = SHIPPING_PROVINCES.find((item) => item.value === provinceValue)
  return province ? province.districts : []
}

export const getWardsByDistrict = (provinceValue, districtValue) => {
  const districts = getDistrictsByProvince(provinceValue)
  const district = districts.find((d) => d.value === districtValue)
  return district ? district.wards : []
}