#spring.application.name=treeshopmanagingsystem
#spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/app}
#spring.datasource.username=${POSTGRES_USER:postgres}
#spring.datasource.password=${POSTGRES_PASSWORD:example}
#spring.jpa.hibernate.ddl-auto=validate
#server.address=0.0.0.0
#server.port=8080
#google.client-id=77728042653-077afatlubpg65g1qrvat3sma7n6ak26.apps.googleusercontent.com
## JWT config
#jwt.secret=${JWT_SECRET:a-string-for-testing}
#jwt.lifetime=${JWT_LIFETIME:86400}
#jwt.cookie.name=${JWT_COOKIE_NAME:hihi}

##Gmail OTP
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=daolemanhhunghy@gmail.com
#spring.mail.password=albi umjq kukk ghdg
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

#TODO comment(or delete in future update)
spring.application.name=treeshopmanagingsystem
#TODO: remove fixed value when migrate to docker
spring.datasource.url=jdbc:postgresql://localhost:5432/app
spring.datasource.username=${POSTGRES_USER:sa}
spring.datasource.password=${POSTGRES_PASSWORD:example}
spring.jpa.hibernate.ddl-auto=validate
server.address=0.0.0.0
server.port=8081
google.client-id=77728042653-077afatlubpg65g1qrvat3sma7n6ak26.apps.googleusercontent.com
# JWT config
jwt.secret=${JWT_SECRET:a-string-for-testing}
jwt.lifetime=${JWT_LIFETIME:86400}
jwt.cookie.name=${JWT_COOKIE_NAME:hihi}

#Gmail OTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=daolemanhhunghy@gmail.com
spring.mail.password=albi umjq kukk ghdg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true